markdown: rdiscount
permalink: /:title

title: "@wizcabbit"

url: http://blog.cabbit.me
is_debug: false

author_info: <a href="http://blog.cabbit.me/">wizcabbit</a>

defaults:
  -
    scope:
      path: "leetcode"
      type: "posts"
    values:
      layout: "post"
      categories: "leetcode"

exclude: ["node_modules", "css", "js", "package.json", "Gruntfile.js", ".gitignore", "README.md"]
