markdown: rdiscount
paginate: 8
permalink: /:title

title: "@wizcabbit"
# url: http://blog.cabbit.me
url: http://localhost:9007
author_info: <a href="http://blog.cabbit.me/">wizcabbit</a>

defaults:
  -
    scope:
      path: "leetcode"
      type: "posts"
    values:
      layout: "post"
      categories: "leetcode"
